Fix following compile error. ---------------------------------------- Exception in thread "main" java.io.IOException: java.lang.reflect.InvocationTargetException 	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:411) 	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:388) 	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:269) 	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:192) 	at main.java.org.bigdata.hbase.spring.HBaseConnection.main(HBaseConnection.java:63) Caused by: java.lang.reflect.InvocationTargetException 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) 	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:409) 	... 4 more Caused by: java.lang.NoSuchMethodError: org.cloudera.htrace.Trace.startSpan(Ljava/lang/String;)Lorg/cloudera/htrace/TraceScope; 	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:195) 	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:479) 	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65) 	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83) 	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:852) 	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:657) 	... 9 more ----------------------------------------